version: 0.0.1   # Required
apimServiceName: Microservice-Governance-Demo-API   # Required, must match name of an apim service deployed in the specified resource group
apiVersionSets:   # Optional
  - id: stmVersionSetID
    displayName: StudentManagementAPIVersionSet
    description: a description
    versioningScheme: Query
    versionQueryName: versionQuery
    versionHeaderName: versionHeader
apis:
  - name: studentmanagement   # Required
    type: http  # http or SOAP
    displayName: student management domain system
    description: student management domain system, which includes CRUD operations.
    # serviceUrl: Absolute URL of the backend service implementing this API.
    openApiSpec: C:\Dev\Projects\StudentManagement\api\openapi.json    # Required, can be url or local file
    openApiSpecFormat: OpenApi30_Json
    policy: C:\Dev\Projects\StudentManagement\apitemplate\apiPolicyHeaders.xml   # Optional, can be url or local file
    suffix: stm  # Required
    apiVersion: v1   # Optional
    apiVersionDescription: My first version   # Optional
    apiVersionSetId: stmVersionSetID
    revision: 1   # Optional
    revisionDescription: My first revision   # Optional
    operations:   # Optional
      getStudents: # Must match the operationId property of a path's operations
        policy: C:\Dev\Projects\StudentManagement\apitemplate\operationRateLimit.xml   # Optional, can be url or local file
      getStudentByID:  # Must match the operationId property of a path's operations
        policy: C:\Dev\Projects\StudentManagement\apitemplate\operationRateLimit.xml   # Optional, can be url or local file
      createStudent: # Must match the operationId property of a path's operations
        policy: C:\Dev\Projects\StudentManagement\apitemplate\operationRateLimit.xml   # Optional, can be url or local file
      updateStudent:  # Must match the operationId property of a path's operations
        policy: C:\Dev\Projects\StudentManagement\apitemplate\operationRateLimit.xml   # Optional, can be url or local file
      deleteStudent:  # Must match the operationId property of a path's operations
        policy: C:\Dev\Projects\StudentManagement\apitemplate\operationRateLimit.xml   # Optional, can be url or local file
    authenticationSettings:   # Optional
      subscriptionKeyRequired: false
      #oAuth2:
      #    authorizationServerId: apimgmtaad
      #    scope: scope
    products: starter    # Optional, adds api to the specified products
outputLocation: C:\Dev\Projects\StudentManagement\api   # Required, folder the creator will write the templates to
linked: true   # Optional
linkedTemplatesBaseUrl : https://servicemeshstorage.blob.core.windows.net/stm-api-templates/api  # Required if 'linked' property is set to true