


CREATE TABLE student (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 
    PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    age NUMBER,
    course VARCHAR2(50) NOT NULL
 );
 
 insert into student (name, age, course) VALUES ( 'arthur', 40, 'CS')
 